const { addDynamicIconSelectors } = require("@iconify/tailwind");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./layouts/**/*.html"],
  theme: {
    // container: {
    //   center: true,
    // },
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--md-sys-color-primary-light)",
          light: "var(--md-sys-color-primary-light)",
          "on-light": "var(--md-sys-color-on-primary-light)",
          container: "var(--md-sys-color-primary-container-light)",
          "on-container": "var(--md-sys-color-on-primary-container-light)",
          "container-light": "var(--md-sys-color-primary-container-light)",
          "on-container-light":
            "var(--md-sys-color-on-primary-container-light)",
          dark: "var(--md-sys-color-primary-dark)",
          "on-dark": "var(--md-sys-color-on-primary-dark)",
          "container-dark": "var(--md-sys-color-primary-container-dark)",
          "on-container-dark": "var(--md-sys-color-on-primary-container-dark)",
          0: "var(--md-ref-palette-primary0)",
          5: "var(--md-ref-palette-primary5)",
          10: "var(--md-ref-palette-primary10)",
          15: "var(--md-ref-palette-primary15)",
          20: "var(--md-ref-palette-primary20)",
          25: "var(--md-ref-palette-primary25)",
          30: "var(--md-ref-palette-primary30)",
          35: "var(--md-ref-palette-primary35)",
          40: "var(--md-ref-palette-primary40)",
          50: "var(--md-ref-palette-primary50)",
          60: "var(--md-ref-palette-primary60)",
          70: "var(--md-ref-palette-primary70)",
          80: "var(--md-ref-palette-primary80)",
          90: "var(--md-ref-palette-primary90)",
          95: "var(--md-ref-palette-primary95)",
          98: "var(--md-ref-palette-primary98)",
          99: "var(--md-ref-palette-primary99)",
          100: "var(--md-ref-palette-primary100)",
        },
        secondary: {
          DEFAULT: "var(--md-sys-color-secondary-light)",
          light: "var(--md-sys-color-secondary-light)",
          "on-light": "var(--md-sys-color-on-secondary-light)",
          container: "var(--md-sys-color-secondary-container-light)",
          "on-container": "var(--md-sys-color-on-secondary-container-light)",
          "container-light": "var(--md-sys-color-secondary-container-light)",
          "on-container-light":
            "var(--md-sys-color-on-secondary-container-light)",
          dark: "var(--md-sys-color-secondary-dark)",
          "on-dark": "var(--md-sys-color-on-secondary-dark)",
          "container-dark": "var(--md-sys-color-secondary-container-dark)",
          "on-container-dark":
            "var(--md-sys-color-on-secondary-container-dark)",
          0: "var(--md-ref-palette-secondary0)",
          5: "var(--md-ref-palette-secondary5)",
          10: "var(--md-ref-palette-secondary10)",
          15: "var(--md-ref-palette-secondary15)",
          20: "var(--md-ref-palette-secondary20)",
          25: "var(--md-ref-palette-secondary25)",
          30: "var(--md-ref-palette-secondary30)",
          35: "var(--md-ref-palette-secondary35)",
          40: "var(--md-ref-palette-secondary40)",
          50: "var(--md-ref-palette-secondary50)",
          60: "var(--md-ref-palette-secondary60)",
          70: "var(--md-ref-palette-secondary70)",
          80: "var(--md-ref-palette-secondary80)",
          90: "var(--md-ref-palette-secondary90)",
          95: "var(--md-ref-palette-secondary95)",
          98: "var(--md-ref-palette-secondary98)",
          99: "var(--md-ref-palette-secondary99)",
          100: "var(--md-ref-palette-secondary100)",
        },
        tertiary: {
          DEFAULT: "var(--md-sys-color-tertiary-light)",
          light: "var(--md-sys-color-tertiary-light)",
          "on-light": "var(--md-sys-color-on-tertiary-light)",
          container: "var(--md-sys-color-tertiary-container-light)",
          "on-container": "var(--md-sys-color-on-tertiary-container-light)",
          "container-light": "var(--md-sys-color-tertiary-container-light)",
          "on-container-light":
            "var(--md-sys-color-on-tertiary-container-light)",
          dark: "var(--md-sys-color-tertiary-dark)",
          "on-dark": "var(--md-sys-color-on-tertiary-dark)",
          "container-dark": "var(--md-sys-color-tertiary-container-dark)",
          "on-container-dark": "var(--md-sys-color-on-tertiary-container-dark)",
          0: "var(--md-ref-palette-tertiary0)",
          5: "var(--md-ref-palette-tertiary5)",
          10: "var(--md-ref-palette-tertiary10)",
          15: "var(--md-ref-palette-tertiary15)",
          20: "var(--md-ref-palette-tertiary20)",
          25: "var(--md-ref-palette-tertiary25)",
          30: "var(--md-ref-palette-tertiary30)",
          35: "var(--md-ref-palette-tertiary35)",
          40: "var(--md-ref-palette-tertiary40)",
          50: "var(--md-ref-palette-tertiary50)",
          60: "var(--md-ref-palette-tertiary60)",
          70: "var(--md-ref-palette-tertiary70)",
          80: "var(--md-ref-palette-tertiary80)",
          90: "var(--md-ref-palette-tertiary90)",
          95: "var(--md-ref-palette-tertiary95)",
          98: "var(--md-ref-palette-tertiary98)",
          99: "var(--md-ref-palette-tertiary99)",
          100: "var(--md-ref-palette-tertiary100)",
        },
        neutral: {
          0: "var(--md-ref-palette-neutral0)",
          5: "var(--md-ref-palette-neutral5)",
          10: "var(--md-ref-palette-neutral10)",
          15: "var(--md-ref-palette-neutral15)",
          20: "var(--md-ref-palette-neutral20)",
          25: "var(--md-ref-palette-neutral25)",
          30: "var(--md-ref-palette-neutral30)",
          35: "var(--md-ref-palette-neutral35)",
          40: "var(--md-ref-palette-neutral40)",
          50: "var(--md-ref-palette-neutral50)",
          60: "var(--md-ref-palette-neutral60)",
          70: "var(--md-ref-palette-neutral70)",
          80: "var(--md-ref-palette-neutral80)",
          90: "var(--md-ref-palette-neutral90)",
          95: "var(--md-ref-palette-neutral95)",
          98: "var(--md-ref-palette-neutral98)",
          99: "var(--md-ref-palette-neutral99)",
          100: "var(--md-ref-palette-neutral100)",
        },
        "neutral-variant": {
          0: "var(--md-ref-palette-neutral-variant0)",
          5: "var(--md-ref-palette-neutral-variant5)",
          10: "var(--md-ref-palette-neutral-variant10)",
          15: "var(--md-ref-palette-neutral-variant15)",
          20: "var(--md-ref-palette-neutral-variant20)",
          25: "var(--md-ref-palette-neutral-variant25)",
          30: "var(--md-ref-palette-neutral-variant30)",
          35: "var(--md-ref-palette-neutral-variant35)",
          40: "var(--md-ref-palette-neutral-variant40)",
          50: "var(--md-ref-palette-neutral-variant50)",
          60: "var(--md-ref-palette-neutral-variant60)",
          70: "var(--md-ref-palette-neutral-variant70)",
          80: "var(--md-ref-palette-neutral-variant80)",
          90: "var(--md-ref-palette-neutral-variant90)",
          95: "var(--md-ref-palette-neutral-variant95)",
          98: "var(--md-ref-palette-neutral-variant98)",
          99: "var(--md-ref-palette-neutral-variant99)",
          100: "var(--md-ref-palette-neutral-variant100)",
        },
        error: {
          DEFAULT: "var(--md-sys-color-error-light)",
          light: "var(--md-sys-color-error-light)",
          "on-light": "var(--md-sys-color-on-error-light)",
          container: "var(--md-sys-color-error-container-light)",
          "on-container": "var(--md-sys-color-on-error-container-light)",
          "container-light": "var(--md-sys-color-error-container-light)",
          "on-container-light": "var(--md-sys-color-on-error-container-light)",
          dark: "var(--md-sys-color-error-dark)",
          "on-dark": "var(--md-sys-color-on-error-dark)",
          "container-dark": "var(--md-sys-color-error-container-dark)",
          "on-container-dark": "var(--md-sys-color-on-error-container-dark)",
          0: "var(--md-ref-palette-error0)",
          5: "var(--md-ref-palette-error5)",
          10: "var(--md-ref-palette-error10)",
          15: "var(--md-ref-palette-error15)",
          20: "var(--md-ref-palette-error20)",
          25: "var(--md-ref-palette-error25)",
          30: "var(--md-ref-palette-error30)",
          35: "var(--md-ref-palette-error35)",
          40: "var(--md-ref-palette-error40)",
          50: "var(--md-ref-palette-error50)",
          60: "var(--md-ref-palette-error60)",
          70: "var(--md-ref-palette-error70)",
          80: "var(--md-ref-palette-error80)",
          90: "var(--md-ref-palette-error90)",
          95: "var(--md-ref-palette-error95)",
          98: "var(--md-ref-palette-error98)",
          99: "var(--md-ref-palette-error99)",
          100: "var(--md-ref-palette-error100)",
        },
        background: {
          DEFAULT: "var(--md-sys-color-background-light)",
          light: "var(--md-sys-color-background-light)",
          dark: "var(--md-sys-color-background-dark)",
        },
        "on-background": {
          DEFAULT: "var(--md-sys-color-on-background-light)",
          light: "var(--md-sys-color-on-background-light)",
          dark: "var(--md-sys-color-on-background-dark)",
        },
        surface: {
          DEFAULT: "var(--md-sys-color-surface-light)",
          light: "var(--md-sys-color-surface-light)",
          dark: "var(--md-sys-color-surface-dark)",
        },
        "on-surface": {
          DEFAULT: "var(--md-sys-color-on-surface-light)",
          light: "var(--md-sys-color-on-surface-light)",
          dark: "var(--md-sys-color-on-surface-dark)",
        },
        "surface-variant": {
          DEFAULT: "var(--md-sys-color-surface-variant-light)",
          light: "var(--md-sys-color-surface-variant-light)",
          dark: "var(--md-sys-color-surface-variant-dark)",
        },
        "on-surface-variant": {
          DEFAULT: "var(--md-sys-color-on-surface-variant-light)",
          light: "var(--md-sys-color-on-surface-variant-light)",
          dark: "var(--md-sys-color-on-surface-variant-dark)",
        },
        outline: {
          DEFAULT: "var(--md-sys-color-outline-light)",
          light: "var(--md-sys-color-outline-light)",
          dark: "var(--md-sys-color-outline-dark)",
        },
        shadow: {
          DEFAULT: "var(--md-sys-color-shadow-light)",
          light: "var(--md-sys-color-shadow-light)",
          dark: "var(--md-sys-color-shadow-dark)",
        },
      },
    },
  },
  plugins: [
    // Iconify plugin
    addDynamicIconSelectors(),
  ],
  corePlugins: {
    container: false,
  },
};
